package com.windawn.kite.dao;

import com.windawn.kite.model.SysJob;

public interface SysJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int insert(SysJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int insertSelective(SysJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    SysJob selectByPrimaryKey(Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysJob record);
}